server:
  port: 8082
spring:
  application:
    name: feigntest
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
servlet:
  content-type: text/html
  cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka